// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBikYGGDXN8x-Yo0kXSQsgEw-yaAHXG3G8',
    appId: '1:723125597778:web:8bbcd3ba4786ddbeb0d18b',
    messagingSenderId: '723125597778',
    projectId: 'ecommerapp-a3700',
    authDomain: 'ecommerapp-a3700.firebaseapp.com',
    storageBucket: 'ecommerapp-a3700.firebasestorage.app',
    measurementId: 'G-8W8WWF1L2V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP3sSb2oTXASCsxhfGVTOLByQsYmN22VI',
    appId: '1:723125597778:android:b83aa8fc2e8944a1b0d18b',
    messagingSenderId: '723125597778',
    projectId: 'ecommerapp-a3700',
    storageBucket: 'ecommerapp-a3700.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD91gKpVXG1bvyxjwpuhQoVJyJlBT4YBU8',
    appId: '1:723125597778:ios:e305a51e8d2275f2b0d18b',
    messagingSenderId: '723125597778',
    projectId: 'ecommerapp-a3700',
    storageBucket: 'ecommerapp-a3700.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceComputerClient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD91gKpVXG1bvyxjwpuhQoVJyJlBT4YBU8',
    appId: '1:723125597778:ios:e305a51e8d2275f2b0d18b',
    messagingSenderId: '723125597778',
    projectId: 'ecommerapp-a3700',
    storageBucket: 'ecommerapp-a3700.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceComputerClient',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBikYGGDXN8x-Yo0kXSQsgEw-yaAHXG3G8',
    appId: '1:723125597778:web:f2a5e0445eec1ecdb0d18b',
    messagingSenderId: '723125597778',
    projectId: 'ecommerapp-a3700',
    authDomain: 'ecommerapp-a3700.firebaseapp.com',
    storageBucket: 'ecommerapp-a3700.firebasestorage.app',
    measurementId: 'G-TJCT1KEJ9K',
  );
}
